### ISSUE TITLE
Link to Data folder in Documents causes issues with cloud backup solutions

### ISSUE THREAD

**Issue by okolvik** [Nexus-Mods/game-starfield#10]
When having Documents synced in OneDrive, the new link to the Data-folder causes OneDrive to sync everything in that folder. Basically filling OneDrive with all the game data.

Might also be a thing for other services like Dropbox.

Would be best if this was optional or solved another way.

**Comment by CDAGaming** [comment]
Very upsetting this issue was ignored, and that most pack developers are instead suggesting to just uninstall or disable Onedrive (Or related services).

There definitly should have been a better solution for this. For me, I removed the crummy junction so my onedrive isn't full of 40GB+ of starfield data

**Comment by insomnious** [comment]
Removed with the 0.4.1 hotfix while we work towards a better solution
