### ISSUE TITLE
Add support for mods that have to be deployed to Documents\My Games\Starfield

### ISSUE THREAD

**Issue by Braste** [Nexus-Mods/game-starfield#2]
Texture mods need to be deployed to "%USERPROFILE%\Documents\My Games\Starfield", not the game folder. At the moment this mods have to be installed manually, because all mod types deploy to the game folder.

**Comment by Pickysaurus** [comment]
This is unlikely to happen but a workaround might be possible (delete/move the new folder and create a link in its place back to the game folder - hopefully tricking the game to use one folder instead of two)

**Comment by ccresz** [comment]
> This is unlikely to happen but a workaround might be possible (delete/move the new folder and create a link in its place back to the game folder - hopefully tricking the game to use one folder instead of two)

Thank you!, This actually worked for me, this are the steps I followed in case someone find them useful.

-Go to `"%USERPROFILE%\Documents\My Games"`
-Rename `Starfield` Folder to `Starfield_bk`
-Copy the contents of the `Starfield_bk` folder to your Game folder (where `starfield.exe` is, usually `"C:\Program Files (x86)\Steam\steamapps\common\Starfield"`)
-Open `cmd` as administrator and (replace with your username) run  `mklink /d "C:\Users\**ReplaceWithYourUsername**\Documents\My Games\Starfield" "C:\Program Files (x86)\Steam\steamapps\common\Starfield"`
-Open Vortex, Go to settings, select hardlink method, and click on apply, deploy mods

That's it, mods are now loading

**Comment by AngellusMortis** [comment]
Slightly better steps:

1. Go to `%USERPROFILE%\Documents\My Games\Starfield`
2. If you have a Data folder, move it to `Starfield\Data` inside of your Steam install. This will ensure you keep all of your screenshots and everything are not lost.
3. Open Command Prompt and run the following command (replace `Path\To\Starfield\Data` with your Steam install location).

```batch
mklink /j "%USERPROFILE%\Documents\My Games\Starfield\Data" "Path\To\Starfield\Data"
```

If everything worked correctly, you should be able to go to %USERPROFILE%\Documents\My Games\Starfield\Data and see the files inside of your Steam install folder.

Note: _In theory_ this method may require Starfield to run as admin to save screenshots if you have it installed in the default library location (`C:\Program Files (x86)\Steam\steamapps\common\Starfield`). I always recommend using a second drive to install Steam games on since it avoids that whole issue.

**Comment by BOTLANNER** [comment]
Alternatively use the SFSE extension to bypass the Documents/My Games folder requirement:
https://github.com/shad0wshayd3/BakaKillMyGames/tree/main (https://www.nexusmods.com/starfield/mods/1599)

**Comment by Pickysaurus** [comment]
An automated fix is in progress here: https://github.com/Nexus-Mods/game-starfield/blob/master/src/setup.ts

**Comment by Pickysaurus** [comment]
Should be fixed in 0.4

**Comment by fre-sch** [comment]
As mod author, I regularly encounter comments on mods not working when installed through Vortex. Some of that might be due to user error, but even then there might be more going on than just that. So in the spirit of this (helping users use mods) I've looked into Vortex and how it deals with Starfield - a combination I don't use for myself - and eventually it lead me to this issue. I'll start by recapping and summarizing my observations on this issue:

Bethesda has introduced loading mods and mod related files from `%UserProfile%\Documents\My Game\Starfield\Data`. This works for ESMs, ba2 archives, loose files. I would consider this a great step towards a solution of separating the game installation directory from user added mod files, and makes for easier management of user mod files.

It appears to me, unfortunately, you have decided this is not only something you don't want to support, but it's also something you're now actively clobbering with a very questionable and potentially serious workaround: offering to create a junction from this `%UserProfile%\Documents\My Game\Starfield\Data` directory to the game installation directory. 

Junctions by themselves aren't the issue, they're essentially a power user feature that's long been part of Windows.
Rather one of the problems with this approach is: for most programs this junction appears as regular directory (as is intended), and so some cloud drive solutions like OneDrive or GoogleDrive could potentially attempt to synchronize the whole Starfield\Data installation directory, gigabytes of data. _This is clearly something you're aware of, since you explicitly warn users when enabling this approach_, and even created this page to explain how problematic this approach really is: https://modding.wiki/en/vortex/users/starfield-folder-junction-issues

The other problem is losing the separation of user installed mods and game installed files and the resulting mess of cleaning/configuring/restoring the vanilla game state. Of course, this isn't really much of a concern for you as Vortex developers, since managing this is the whole point of Vortex.

Personally, I would have preferred to see support for having Vortex install mods into `%UserProfile%\Documents\My Game\Starfield\Data` since this simple separation is extremely beneficial, and it's probably the way forward for Bethesda and Starfield.
And while you have gone to great length to make this as workable as possible and document this as much as possible, there are a lot of unknown problems this can cause by the nature of it. 

Understanding the implications of using a junction also requires a certain familiarity of terminology that might not be a given for some number of Vortex users. And as such, it's doubtful they can actually make a meaningful and informed decision without first brushing up on advanced file system management feature of Windows. 

In my opinion, this folder junction setting should not be an actively "advertised" option - as in immediately shown to users on adding Starfield to Vortex as managed game.

In my opinion, the explanations also presents Bethesda's feature of loading from `%UserProfile%\Documents\My Game\Starfield\Data` as a problem, when it can also be considered an improvement. While there's some probably some kind of value to somebody in using a folder junction, to me this runs counter to the principle of both what Bethesda is trying to achieve in providing this, as well as counter to the principle of what Vortex in general is trying to achieve:

Creating a more stable and cleaner way to manage your mods.

Now none of this would really be of any concern, were it not for Vortex being the most visible and prominent mod management tool for mods on nexusmods, and were it not for being a tool for less experienced and less tech-savvy users. **This could potentially create complicated problems for a group of people that are unable to resolve them.**

I had hoped to potentially create a discussion into the process of arriving at the current junction solution and the non-use of this directory in my previous duplicate ticket. Some projects don't like comments on closed issues, some projects are very specific about their wording used in issues, and the summary of this issue isn't exactly clear: technically there are no mods that **have to be** installed into `%UserProfile%\Documents\My Game\Starfield\Data` - it's something that's entirely optional (but beneficial)

**Comment by fre-sch** [comment]
Some more observations:

> This change will require the mod staging folder and game to be on the same drive as My Documents. Which is going to cause a ruckus. https://github.com/Nexus-Mods/game-starfield/pull/4#issuecomment-1711868885

The default behavior of Steam - for example - is to create a library directory in the primary installation directory, eg `C:\Program Files (x86)\Steam\steamapps\common` which already necessitates setting the mod staging area of Vortex to a folder on the same drive - _which by nature of Windows also is the same drive containing the My Documents folder_.

While there are certainly users with advanced enough knowledge to configure themselves a new Steam Library directory on other drives, or install Steam itself on another drive, or retarget their user home to another drive, the default case remains: My Documents, Vortex mod staging area and game installation target _are by default all on one drive_, or rather _must be for Vortex to function_.

And while the link and junction features of Windows clearly have become more stable and solid since Windows 10, having a junction from one drive to another - something which is largely transparent for most programs - can cause various other unknown and intransparent issues to aforementioned cloud drives, disk space calculations, disk cleanup utils, etc. Which like I mentioned earlier might create problems for a majority of users, which might not be skilled enough to identify and deal with those.

What exactly is "cause a ruckus"? What are the specific problems with using `My Documents\My Games\Starfield\Data`? What is the severity of this "ruckus", that it justifies implementing an even more known-to-be-problematic approach (as is evident per the wiki article)? I would expect these severe problems to be mentioned when such a drastic measure as clobbering a directory with junctions potentially across drives is the prominent choice of Vortex. 

Judging from https://github.com/Nexus-Mods/game-starfield/pull/4, there's not even a dramatic code change required, albeit this could be just a prototype implementation with the final release code being more involved than that.

So far I have only seen a really bad solution to a non-existent problem with absolutely no good reasons. Any reasons I have seen are equally valid for any combination of installation directory of the game and Vortex staging area and Vortex deployment target area.
